-- MySQL Script generated by MySQL Workbench
-- 01/25/18 11:06:37
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema diplomkatalog
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `diplomkatalog` ;

-- -----------------------------------------------------
-- Schema diplomkatalog
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `diplomkatalog` DEFAULT CHARACTER SET utf8 ;
USE `diplomkatalog` ;

-- -----------------------------------------------------
-- Table `diplomkatalog`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `diplomkatalog`.`users` ;

CREATE TABLE IF NOT EXISTS `diplomkatalog`.`users` (
  `email` VARCHAR(100) NOT NULL,
  `passhash` VARCHAR(256) NOT NULL,
  PRIMARY KEY (`email`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `diplomkatalog`.`themas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `diplomkatalog`.`themas` ;

CREATE TABLE IF NOT EXISTS `diplomkatalog`.`themas` (
  `idthema` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `leiter` VARCHAR(100) NOT NULL,
  `betreuer` VARCHAR(100) NOT NULL,
  `projektleiterText` VARCHAR(256) NULL,
  `projektleiterImage` VARCHAR(256) NULL,
  PRIMARY KEY (`idthema`),
  INDEX `fk_themas_users_idx` (`leiter` ASC),
  INDEX `fk_themas_users1_idx` (`betreuer` ASC),
  CONSTRAINT `fk_themas_users`
    FOREIGN KEY (`leiter`)
    REFERENCES `diplomkatalog`.`users` (`email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_themas_users1`
    FOREIGN KEY (`betreuer`)
    REFERENCES `diplomkatalog`.`users` (`email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `diplomkatalog`.`mitarbeiter`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `diplomkatalog`.`mitarbeiter` ;

CREATE TABLE IF NOT EXISTS `diplomkatalog`.`mitarbeiter` (
  `idMitarbeiterTexts` INT NOT NULL AUTO_INCREMENT,
  `themas_idthema` INT NOT NULL,
  `text` VARCHAR(256) NULL,
  `image` VARCHAR(256) NULL,
  PRIMARY KEY (`idMitarbeiterTexts`, `themas_idthema`),
  INDEX `fk_MitarbeiterTexts_themas1_idx` (`themas_idthema` ASC),
  CONSTRAINT `fk_MitarbeiterTexts_themas1`
    FOREIGN KEY (`themas_idthema`)
    REFERENCES `diplomkatalog`.`themas` (`idthema`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `diplomkatalog`.`technologies`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `diplomkatalog`.`technologies` ;

CREATE TABLE IF NOT EXISTS `diplomkatalog`.`technologies` (
  `idtechnologies` INT NOT NULL,
  `themas_idthema` INT NOT NULL,
  `text` VARCHAR(256) NULL,
  `image` VARCHAR(256) NULL,
  PRIMARY KEY (`idtechnologies`, `themas_idthema`),
  INDEX `fk_technologies_themas1_idx` (`themas_idthema` ASC),
  CONSTRAINT `fk_technologies_themas1`
    FOREIGN KEY (`themas_idthema`)
    REFERENCES `diplomkatalog`.`themas` (`idthema`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
